# Package/heatpump_core.yaml  (Tank Average poistettu – se on nyt heatpump_tank.yaml)
# P_el / P_th / dT / COP (display/gauge) / Pulse alias / Running / Last On-Off

input_number:
  hp_virtaus:
    name: "HP virtaus"
    min: 0.10
    max: 4.00
    step: 0.01
    unit_of_measurement: "m³/h"
    mode: box
    icon: mdi:water

input_datetime:
  hp_run_start: { name: "HP käynnin aloitus", has_date: true, has_time: true }
  hp_run_end:   { name: "HP käynnin lopetus", has_date: true, has_time: true }

input_select:
  hp_season_mode:
    name: "HP kausitila"
    options: ["Talvi", "Kesä"]
    icon: mdi:calendar

input_boolean:
  hp_force_lower_sensor:
    name: "Käytä alempaa anturia (ohjaus)"
    icon: mdi:arrow-down

automation:
  - id: hp_run_start_timestamp
    alias: "HP – käynnin aloitushetki"
    trigger: { platform: state, entity_id: binary_sensor.heatpump_running, to: "on" }
    action:
      - service: input_datetime.set_datetime
        target: { entity_id: input_datetime.hp_run_start }
        data: { datetime: "{{ now().isoformat() }}" }

  - id: hp_run_end_timestamp
    alias: "HP – käynnin lopetushetki"
    trigger: { platform: state, entity_id: binary_sensor.heatpump_running, to: "off" }
    action:
      - service: input_datetime.set_datetime
        target: { entity_id: input_datetime.hp_run_end }
        data: { datetime: "{{ now().isoformat() }}" }

template:
  - sensor:
      - name: "Heatpump Power"
        unique_id: heatpump_power
        unit_of_measurement: "kW"
        device_class: power
        state_class: measurement
        state: >
          {% set v = states('sensor.techroom_esp32_heat_pump_power') %}
          {{ v|float(0) if v not in ['unknown','unavailable','', none] else 0 }}

      - name: "Heatpump Heat Power"
        unique_id: heatpump_heat_power
        unit_of_measurement: "kW"
        device_class: power
        state_class: measurement
        state: >
          {% set v = states('sensor.techroom_esp32_hp