# P_el / P_th / dT / COP / Tank kerrokset / Tank Average / Running / Last On-Off

input_number:
  hp_virtaus:
    name: "HP virtaus"
    min: 0.10
    max: 4.00
    step: 0.01
    unit_of_measurement: "m³/h"
    mode: box
    icon: mdi:water

input_datetime:
  hp_run_start:
    name: "HP käynnin aloitus"
    has_date: true
    has_time: true
  hp_run_end:
    name: "HP käynnin lopetus"
    has_date: true
    has_time: true

input_select:
  hp_season_mode:
    name: "HP kausitila"
    options: ["Talvi", "Kesä"]
    icon: mdi:calendar

input_boolean:
  hp_force_lower_sensor:
    name: "Käytä alempaa anturia (ohjaus)"
    icon: mdi:arrow-down

automation:
  - id: hp_run_start_timestamp
    alias: "HP – käynnin aloitushetki"
    trigger: { platform: state, entity_id: binary_sensor.heatpump_running, to: "on" }
    action:
      - service: input_datetime.set_datetime
        target: { entity_id: input_datetime.hp_run_start }
        data: { datetime: "{{ now().isoformat() }}" }

  - id: hp_run_end_timestamp
    alias: "HP – käynnin lopetushetki"
    trigger: { platform: state, entity_id: binary_sensor.heatpump_running, to: "off" }
    action:
      - service: input_datetime.set_datetime
        target: { entity_id: input_datetime.hp_run_end }
        data: { datetime: "{{ now().isoformat() }}" }

template:
  - sensor:
      - name: "Heatpump Power"
        unique_id: heatpump_power
        unit_of_measurement: "kW"
        device_class: power
        state_class: measurement
        state: >
          {% set v = states('sensor.techroom_esp32_heat_pump_power') %}
          {{ v|float(0) if v not in ['unknown','unavailable','', none] else 0 }}

      - name: "Heatpump Heat Power"
        unique_id: heatpump_heat_power
        unit_of_measurement: "kW"
        device_class: power
        state_class: measurement
        state: >
          {% set v = states('sensor.techroom_esp32_hp_lampoteho') %}
          {{ v|float(0) if v not in ['unknown','unavailable','', none] else 0 }}

      - name: "Heatpump Delta T"
        unique_id: heatpump_delta_t
        unit_of_measurement: "°C"
        state_class: measurement
        state: >
          {% set v = states('sensor.techroom_esp32_hp_delta_t') %}
          {{ v|float if v not in ['unknown','unavailable','', none] else 'unknown' }}

      - name: "HP Pulse Rate Alias"
        unique_id: hp_pulse_rate_alias
        icon: mdi:pulse
        unit_of_measurement: "imp/min"
        state_class: measurement
        state: >
          {% set v = states('sensor.techroom_esp32_hp_pulse_rate') %}
          {{ (v|float(0)|round(0)) if v not in ['unknown','unavailable','', none] else 0 }}

      - name: "Heatpump Brine Delta T (display)"
        unique_id: heatpump_brine_delta_t_display
        unit_of_measurement: "°C"
        state_class: measurement
        state: >
          {% set raw = states('sensor.techroom_esp32_hp_brine_delta_t_raw') %}
          {% set filt= states('sensor.techroom_esp32_hp_brine_delta_t') %}
          {% if raw not in ['unknown','unavailable','', none] %}{{ raw|float|round(2) }}
          {% elif filt not in ['unknown','unavailable','', none] %}{{ filt|float|round(2) }}
          {% else %} unknown {% endif %}

      - name: "Heatpump COP (display)"
        unique_id: heatpump_cop_display
        state: >
          {% if is_state('binary_sensor.heatpump_running','on') %}
            {% set v = states('sensor.techroom_esp32_heat_pump_cop') %}
            {% if v not in ['unknown','unavailable','', none] %}{{ v|float(0)|round(2) }}{% else %}unknown{% endif %}
          {% else %} unknown {% endif %}

      - name: "Heatpump COP (gauge)"
        unique_id: heatpump_cop_gauge
        unit_of_measurement: ""
        state_class: measurement
        state: >
          {% if is_state('binary_sensor.heatpump_running','on') %}
            {% set v = states('sensor.techroom_esp32_heat_pump_cop') %}
            {{ v|float(0)|round(2) if v not in ['unknown','unavailable','', none] else 0 }}
          {% else %} 0 {% endif %}

      # Tank kerrokset
      - name: "Heatpump Tank Top"
        unique_id: heatpump_tank_top
        unit_of_measurement: "°C"
        state_class: measurement
        state: >
          {% set v = states('sensor.techroom_esp32_varaaja_yla') %}
          {{ (v|float(0)|round(1)) if v not in ['unknown','unavailable','', none] else 'unknown' }}
      - name: "Heatpump Tank Mid Top"
        unique_id: heatpump_tank_mid_top
        unit_of_measurement: "°C"
        state_class: measurement
        state: >
          {% set v = states('sensor.techroom_esp32_varaaja_keski_yla') %}
          {{ (v|float(0)|round(1)) if v not in ['unknown','unavailable','', none] else 'unknown' }}
      - name: "Heatpump Tank Mid Bottom"
        unique_id: heatpump_tank_mid_bottom
        unit_of_measurement: "°C"
        state_class: measurement
        state: >
          {% set v = states('sensor.techroom_esp32_varaaja_keski_ala') %}
          {{ (v|float(0)|round(1)) if v not in ['unknown','unavailable','', none] else 'unknown' }}
      - name: "Heatpump Tank Bottom"
        unique_id: heatpump_tank_bottom
        unit_of_measurement: "°C"
        state_class: measurement
        state: >
          {% set v = states('sensor.techroom_esp32_varaaja_ala') %}
          {{ (v|float(0)|round(1)) if v not in ['unknown','unavailable','', none] else 'unknown' }}

      # Käynnit & analytiikka (aliasit)
      - name: "Heatpump Start Count"
        unique_id: heatpump_start_count
        state_class: measurement
        state: "{{ states('sensor.hp_kaynnit_tanaan')|int(0) }}"
      - name: "Heatpump Avg Run Time"
        unique_id: heatpump_avg_run_time
        unit_of_measurement: "min"
        state_class: measurement
        state: >
          {% set t_h = states('sensor.hp_kayntiaika_tanaan')|float(0) %}
          {% set c   = states('sensor.hp_kaynnit_tanaan')|int(0) %}
          {{ ((t_h * 60) / c)|round(1) if c > 0 else 0 }}

  - trigger:
      - platform: state
        entity_id:
          - sensor.heatpump_tank_top
          - sensor.heatpump_tank_mid_top
          - sensor.heatpump_tank_mid_bottom
          - sensor.heatpump_tank_bottom
    sensor:
      - name: "Heatpump Tank Average"
        unique_id: heatpump_tank_average
        unit_of_measurement: "°C"
        device_class: temperature
        state_class: measurement
        availability: >
          {% set s = [
            states('sensor.heatpump_tank_top')|float(default=nan),
            states('sensor.heatpump_tank_mid_top')|float(default=nan),
            states('sensor.heatpump_tank_mid_bottom')|float(default=nan),
            states('sensor.heatpump_tank_bottom')|float(default=nan)
          ] %}
          {{ s | select('is_number') | list | length == 4 }}
        state: >
          {% set top = states('sensor.heatpump_tank_top')|float %}
          {% set mt  = states('sensor.heatpump_tank_mid_top')|float %}
          {% set mb  = states('sensor.heatpump_tank_mid_bottom')|float %}
          {% set bot = states('sensor.heatpump_tank_bottom')|float %}
          {{ ((top + mt + mb + bot) / 4) | round(2) }}

  - trigger:
      - platform: state
        entity_id: binary_sensor.heatpump_running
        to: "on"
    sensor:
      - name: "Heatpump Last Run Started"
        unique_id: heatpump_last_run_started_ts
        device_class: timestamp
        icon: mdi:clock-start
        state: "{{ now().isoformat() }}"
        attributes: { source: "binary_sensor.heatpump_running" }

  - trigger:
      - platform: state
        entity_id: binary_sensor.heatpump_running
        to: "off"
    sensor:
      - name: "Heatpump Last Off Started"
        unique_id: heatpump_last_off_started_ts
        device_class: timestamp
        icon: mdi:clock-end
        state: "{{ now().isoformat() }}"
        attributes: { source: "binary_sensor.heatpump_running" }

  - trigger:
      - platform: time_pattern
        minutes: "/1"
      - platform: state
        entity_id: sensor.heatpump_last_run_started
    sensor:
      - name: "Heatpump Last Run Time (min)"
        unique_id: heatpump_last_run_time_min_v2
        unit_of_measurement: "min"
        icon: mdi:timer-sand
        state_class: measurement
        state: >
          {% set ts = states('sensor.heatpump_last_run_started') %}
          {% if ts in ['unknown','unavailable','none','None',''] %} 0
          {% else %}
            {% set t = as_datetime(ts) %}
            {{ ((now() - t).total_seconds() / 60) | round(1) if t else 0 }}
          {% endif %}

  - trigger:
      - platform: time_pattern
        minutes: "/1"
      - platform: state
        entity_id: sensor.heatpump_last_off_started
    sensor:
      - name: "Heatpump Last Off Time (min)"
        unique_id: heatpump_last_off_time_min_v2
        unit_of_measurement: "min"
        icon: mdi:timer-sand-complete
        state_class: measurement
        state: >
          {% set ts = states('sensor.heatpump_last_off_started') %}
          {% if ts in ['unknown','unavailable','none','None',''] %} 0
          {% else %}
            {% set t = as_datetime(ts) %}
            {{ ((now() - t).total_seconds() / 60) | round(1) if t else 0 }}
          {% endif %}

  - binary_sensor:
      - name: "Heatpump Running"
        unique_id: heatpump_running
        device_class: running
        state: "{{ states('binary_sensor.techroom_esp32_heat_pump_running') }}"
      - name: "Heatpump Tariff Active"
        unique_id: heatpump_tariff_active
        state: "{{ states('binary_sensor.techroom_esp32_tariff_active') }}"
