# Package/heatpump_brine.yaml
# Täällä pidetään vain maaliuokseen liittyvät erityislogiikat (esim. hälytykset).
# Sensorit tulevat suoraan ESPHomen kautta (sensor.hp_liuos_meno jne.)

automation:
  - id: hp_brine_low_temp_alert
    alias: "Hälytys: Maaliuos liian kylmää"
    trigger:
      - platform: numeric_state
        entity_id: sensor.hp_liuos_meno
        below: -5
    action:
      - service: notify.persistent_notification
        data:
          title: "Lämpöpumppu hälytys"
          message: "Maaliuoksen menolämpötila on laskenut alle -5 asteen!"