# Ottotehon näyttösuodattimet (tc15/tc20/tc30) + UI-clamp

sensor:
  - platform: filter
    name: "Heatpump Power (display)"
    unique_id: heatpump_power_display
    entity_id: sensor.heatpump_power
    filters:
      - filter: lowpass
        time_constant: 20
        precision: 2

  - platform: filter
    name: "Heatpump Power (display, tc15)"
    unique_id: heatpump_power_display_tc15
    entity_id: sensor.heatpump_power
    filters:
      - filter: lowpass
        time_constant: 15
        precision: 2

  - platform: filter
    name: "Heatpump Power (display, tc30)"
    unique_id: heatpump_power_display_tc30
    entity_id: sensor.heatpump_power
    filters:
      - filter: lowpass
        time_constant: 30
        precision: 2

template:
  - sensor:
      # UI: näytä 0.00 kW jos running=off, muuten suodatettu arvo
      - name: "Heatpump Power (display, UI)"
        unique_id: heatpump_power_display_ui
        unit_of_measurement: "kW"
        device_class: power
        state_class: measurement
        state: >
          {% set running = is_state('binary_sensor.heatpump_running','on') %}
          {% set disp = states('sensor.heatpump_power_display')|float(0) %}
          {{ disp if running else 0.0 }}